package com.hotelbooking.dto;

import com.hotelbooking.enums.Role;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(name = "ManagerDTO", description = "Hotel manager registration payload")
public class ManagerDTO {

    // Generated by DB
    @Schema(description = "Manager user id", example = "12")
    private Long u_id;

    @Email
    @NotBlank
    @Schema(description = "Manager email", example = "manager@example.com")
    private String email;

    @NotBlank
    @Size(min = 6)
    @Schema(description = "Manager password", example = "manager123")
    private String password;

    @NotBlank
    @Schema(description = "Manager full name", example = "Alex Manager")
    private String fullName;

    @NotNull
    @Schema(description = "Role for manager account", example = "ROLE_HOTEL_MANAGER")
    private Role role;

    @Schema(description = "Whether account is approved/enabled", example = "false")
    private boolean enabled = false;

    @NotBlank
    @Schema(description = "Hotel name", example = "Sunrise Suites")
    private String hotelName;

    @NotBlank
    @Schema(description = "Hotel city", example = "Bengaluru")
    private String city;

    @NotBlank
    @Size(min = 10)
    @Schema(description = "Hotel description", example = "Business hotel near city center.")
    private String description;

    @Schema(description = "Google Maps URL for hotel", example = "https://maps.google.com/?q=Sunrise+Suites")
    private String mapsURL;
}

