package com.hotelbooking.dto;

import com.hotelbooking.enums.RoomType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(name = "RoomDTO", description = "Room payload")
public class RoomDTO {

    // Generated by DB
    @Schema(description = "Room id", example = "201")
    private Long r_id;

    @NotNull
    @Schema(description = "Room type", example = "DELUXE")
    private RoomType roomType;

    @Positive(message = "Price must be greater than zero")
    @Schema(description = "Nightly room price", example = "2499.00")
    private double pricePerNight;

    @PositiveOrZero(message = "Total rooms must be zero or greater")
    @Schema(description = "Total number of rooms", example = "15")
    private int totalRooms;

    // Derived from totalRooms in service layer
    @Schema(description = "Whether rooms are available", example = "true")
    private boolean availableRooms = true;

    // Hotel reference (set by backend context)
    @Schema(description = "Hotel id owning this room", example = "101")
    private Long hotelId;
}
