package com.hotelbooking.dto;

import com.hotelbooking.enums.Role;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(name = "UserDTO", description = "User registration/update payload")
public class UserDTO {

    // Generated by DB, not from UI
    @Schema(description = "User id", example = "100")
    private Long u_id;

    @Email(message = "Invalid email format")
    @NotBlank(message = "Email is required")
    @Schema(description = "User email", example = "customer@example.com")
    private String email;

    @NotBlank(message = "Password is required")
    @Size(min = 6, message = "Password must be at least 6 characters")
    @Schema(description = "User password", example = "customer123")
    private String password;

    @NotBlank(message = "Full name is required")
    @Schema(description = "User full name", example = "John Customer")
    private String fullName;

    @NotNull(message = "Role is required")
    @Schema(description = "User role", example = "ROLE_USER")
    private Role role;

    // Used by admin approval
    @Schema(description = "Whether account is enabled", example = "true")
    private boolean enabled = true;
}
